#!/bin/env python2.7

import uberscript
import uberscript.types

s = uberscript.UberScript(
  playbook='/opt/uberspace/playbooks/uberspace-add-domain.yml',
  parameters=[
    ('domain', 'd', {
      'help': 'this is the domain to add to your uberspace',
      'type': uberscript.types.domain,
      'required': True,
    }),
    ('webserver', 'w', {
      'help': 'add domain to the webserver configuration',
      'action': 'store_true',
    }),
    ('mailserver', 'm', {
      'help': 'add domain to the mailserver configuration',
      'action': 'store_true'
    }),
    ('namespace', 'e', {
      'help': 'use this namespace when adding a mail domain',
      'type': uberscript.types.restricted_str('a-z0-9'),
      'depends': 'mailserver',
    }),
    ('quiet', 'q', {
      'help': 'quiet (no output)',
      'action': 'store_true',
    }),
  ],
).auto()
